env:

# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[af1b746bb9ac02b151e9cc22cd5f2c1e72f4ac221ad9f9d6c1088acb1777fb22d40b570d4317bbe4ec818a792745fc2e]"
  TG_TOKEN: "ENCRYPTED[3597f9ed4b14e0165badcf3c27994606a228415c1928d73460c018f0f95f1a3630506749a9a01e5f18a6dd7eac9632cb]"
  TG_CHAT_ID: "ENCRYPTED[acf2dd0ff60496ec4b4db081d5d6ec819e6dc9e68d112d9af446f229d5180ee60ba65467a9718542ec5139cf538f5d35]"
  CREDENTIALS: "ENCRYPTED[143795044001b92ac9c40866a59adc156f71a42d2fd92ec175ba65c4617c059e1393e59ca1fc28413ee0a85ad7d4c950]"
  USER: "ENCRYPTED[dea9febbe7cb640a6edc6f7a20f645031ca8b0aa1ba590a717bb3366589feb76d15ef54cda831365347839ce949c76a8]"
  EMAIL: "ENCRYPTED[1d69c0b6b069f46ad9390be8222556371290eee24e11ddb2305b7a827f9598f393a4eeea7c1d8b7fa26c31fb177f21fc]"
  KBUILD_BUILD_USER: "builder"
  KBUILD_BUILD_HOST: "mobxci"
  
# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'AkazaaMoon'
  timeout_in: 120m
  container:
    image: c3eru/gaspoll:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "c3eru"
     - git config --global user.email "yyprjkt@gmail.com"
     - echo "$CREDENTIALS" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - export KBUILD_BUILD_USER=$KBUILD_BUILD_USER
     - export KBUILD_BUILD_HOST=$KBUILD_BUILD_USER
     - export BUILD_USERNAME=$KBUILD_BUILD_USER
     - export BUILD_HOSTNAME=$KBUILD_BUILD_USER


  Sinkronisasi_script:
     - ./sinkronisasi.sh
     
  Build-rom_script:
     - ./membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./mengemas.sh
